module.exports.descriptors = [
    'Floresta',
    'Antigo Parque',
    'Pedreira',
    'Rugido Animal',
    'Cascata',
    'Penhasco',
    'Zona',
    'Várzea',
    'Campo',
    'Mar',
    'Rio',
    'Cachoeira',
    'Trilha',
    'Chalé',
    'Gruta'
]

module.exports.places = [
    'da Lua',
    'do Amor',
    'de Lual',
    'da Vila',
    'da Sorte',
    'do Morro Azul',
    'do Sol',
    'do Leão',
    'da Lua',
    'do Interior',
    'da Luta',
    'do Peixe',
    'do Morcego',
    'da Esperança',
    'da Boa Esperança',
    'Verde',
    'do Nascer do Sol',
    'do Por do Sol',
    'da Pedra Roxa',
    'do Céu Azul',
    'do Vale Verde'
]